### ISSUE TITLE
URI must be a string or UriInterface

### ISSUE THREAD

**Issue by Alisafirzadeh** [PrevailExcel/laravel-nowpayments#1]
Hi
I followed your documentation but I get the following error
**URI must be a string or UriInterface**

**Comment by PrevailExcel** [comment]
> Hi I followed your documentation but I get the following error **URI must be a string or UriInterface**

Add steps to recreate the error please.

**Comment by jontstaz** [comment]
I get the same problem too. When I go to the '/laravel-nowpayments' URL it throws that error.

**Comment by PrevailExcel** [comment]
Please add these to the .env


NOWPAYMENTS_LIVE_URL="https://api.nowpayments.io/v1"
NOWPAYMENTS_SANDBOX_URL="https://api-sandbox.nowpayments.io/v1"
NOWPAYMENTS_ENV="live"
NOWPAYMENTS_API_KEY="Your-API-KEY-Here"
NOWPAYMENTS_CALLBACK_URL="https://mycallback.io"

I'll update the documentation to point this out appropriately. Thank you.

**Comment by PrevailExcel** [comment]
Please add these to the .env


NOWPAYMENTS_LIVE_URL="https://api.nowpayments.io/v1"
NOWPAYMENTS_SANDBOX_URL="https://api-sandbox.nowpayments.io/v1"
NOWPAYMENTS_ENV="sandbox"
NOWPAYMENTS_API_KEY="Your-API-KEY-Here"
NOWPAYMENTS_CALLBACK_URL="https://mycallback.io"

I'll update the documentation to point this out appropriately. Thank you.

**Comment by PrevailExcel** [comment]
Add these to your .env 

NOWPAYMENTS_LIVE_URL="https://api.nowpayments.io/v1"
NOWPAYMENTS_SANDBOX_URL="https://api-sandbox.nowpayments.io/v1"
NOWPAYMENTS_ENV="sandbox"
NOWPAYMENTS_API_KEY="Your-API-Key-Here"
NOWPAYMENTS_CALLBACK_URL="https://mycallback.io"
NOWPAYMENTS_EMAIL="your-email-here"
NOWPAYMENTS_PASSWORD="*******"


You can also add these to the config/nowpayments.php accordingly.
I'll update the documentation to address this properly. Thank you
